development:
  adapter: postgresql
  encoding: unicode
  database: jamify_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: jamify_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: jamify_production
  pool: 5
